// Generated by scripts/configure.mjs from profiles/grab-url.json. Do not edit by hand.

/// Custom URL scheme registered with the OS for the OAuth handoff, or ""
/// when the profile doesn't use one.
pub const DEEP_LINK_SCHEME: &str = "";

/// Origin the main window loads in remote mode, or "" in local mode.
pub const APP_URL: &str = "";

/// Name of the bundled CLI exposed through the `sidecar_output` command,
/// or "" when the profile bundles none.
pub const SIDECAR_NAME: &str = "yt-dlp";

/// The fixed argument list that sidecar is always invoked with. Fixed, and
/// not passed in from the frontend, so the webview can't turn the bundled
/// binary into an arbitrary-argument process spawner.
pub const SIDECAR_ARGS: &[&str] = &["--version"];

/// Fixed flags the `download_media` command prepends before the
/// destination directory and the one caller-supplied URL. Empty when the
/// profile's sidecar is not a downloader, which disables that command.
pub const SIDECAR_DOWNLOAD_ARGS: &[&str] = &["--newline", "--color", "never", "--no-warnings", "--no-playlist", "--continue", "--output", "%(title)s [%(id)s].%(ext)s"];

/// Whether the profile configured auto-updates. False means the updater
/// plugin is never registered — registering it without a `pubkey` in
/// tauri.conf.json panics at startup rather than staying inert.
pub const UPDATER_ENABLED: bool = false;
