
const sidebarConfig = [
 
  {
    type: "category",
    label: "Guide",
    collapsed: false,
    items: [
      {
        type: "autogenerated",
        dirName: "guide",
      },
    ],
  },
  {
    type: "category",
    label: "Grab",
    collapsed: false,
    items: [
      {
        type: "autogenerated",
        dirName: "lib",
      },
    ],
  },
];

export default {
  lib: sidebarConfig,
  default: sidebarConfig,
};
