// This file is generated by @hey-api/openapi-ts and rewired by api2client.
// Everything the SDK sends goes through grab, so caching, retries, rate limiting,
// deduplication and grab.mock apply to every endpoint below.

import { createClient, createConfig, type ClientOptions } from "api2client";

export const client = createClient(
  createConfig<ClientOptions>({
    baseUrl: "https://petstore3.swagger.io/api/v3",
  }),
);
