// This file is generated by @hey-api/openapi-ts.
// One function per operation; `options.client` falls back to the shared client.

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from "api2client";

import { client as _heyApiClient } from "./client.gen";
import type {
  AddPetData,
  AddPetError,
  AddPetResponse,
  FindPetsByStatusData,
  FindPetsByStatusError,
  FindPetsByStatusResponse,
  GetPetByIdData,
  GetPetByIdError,
  GetPetByIdResponse,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  client?: Client;
};

/** Find pet by ID. */
export const getPetById = <ThrowOnError extends boolean = false>(
  options: Options<GetPetByIdData, ThrowOnError>,
) =>
  (options.client ?? _heyApiClient).get<
    GetPetByIdResponse,
    GetPetByIdError,
    ThrowOnError
  >({
    url: "/pet/{petId}",
    ...options,
  });

/** Finds pets by status. */
export const findPetsByStatus = <ThrowOnError extends boolean = false>(
  options?: Options<FindPetsByStatusData, ThrowOnError>,
) =>
  (options?.client ?? _heyApiClient).get<
    FindPetsByStatusResponse,
    FindPetsByStatusError,
    ThrowOnError
  >({
    url: "/pet/findByStatus",
    ...options,
  });

/** Add a new pet to the store. */
export const addPet = <ThrowOnError extends boolean = false>(
  options: Options<AddPetData, ThrowOnError>,
) =>
  (options.client ?? _heyApiClient).post<
    AddPetResponse,
    AddPetError,
    ThrowOnError
  >({
    url: "/pet",
    ...options,
  });
