// This file is generated by @hey-api/openapi-ts.
// Trimmed to the three Petstore operations this example calls.

export type Pet = {
  id?: number;
  name: string;
  status?: "available" | "pending" | "sold";
  photoUrls: Array<string>;
};

export type ApiError = {
  code?: number;
  type?: string;
  message?: string;
};

export type GetPetByIdData = {
  body?: never;
  path: { petId: number };
  query?: never;
  url: "/pet/{petId}";
};

export type GetPetByIdResponse = Pet;
export type GetPetByIdError = ApiError;

export type FindPetsByStatusData = {
  body?: never;
  path?: never;
  query?: { status?: "available" | "pending" | "sold" };
  url: "/pet/findByStatus";
};

export type FindPetsByStatusResponse = Array<Pet>;
export type FindPetsByStatusError = ApiError;

export type AddPetData = {
  body: Pet;
  path?: never;
  query?: never;
  url: "/pet";
};

export type AddPetResponse = Pet;
export type AddPetError = ApiError;
