export default {
  "0a052849": [() => import(/* webpackChunkName: "0a052849" */ "@site/docs/lib/grab-api.md"), "@site/docs/lib/grab-api.md", require.resolveWeak("@site/docs/lib/grab-api.md")],
  "11b43341": [() => import(/* webpackChunkName: "11b43341" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-7fc.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-7fc.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-7fc.json")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1aa5738c": [() => import(/* webpackChunkName: "1aa5738c" */ "@site/docs/lib/modules.md"), "@site/docs/lib/modules.md", require.resolveWeak("@site/docs/lib/modules.md")],
  "292ecbe4": [() => import(/* webpackChunkName: "292ecbe4" */ "@site/docs/lib/log.md"), "@site/docs/lib/log.md", require.resolveWeak("@site/docs/lib/log.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "64be5006": [() => import(/* webpackChunkName: "64be5006" */ "@site/docs/guide/Docs Libraries.md"), "@site/docs/guide/Docs Libraries.md", require.resolveWeak("@site/docs/guide/Docs Libraries.md")],
  "6cebdc36": [() => import(/* webpackChunkName: "6cebdc36" */ "@site/docs/guide/Performance.md"), "@site/docs/guide/Performance.md", require.resolveWeak("@site/docs/guide/Performance.md")],
  "8ff040d2": [() => import(/* webpackChunkName: "8ff040d2" */ "@site/docs/guide/Comparisons.md"), "@site/docs/guide/Comparisons.md", require.resolveWeak("@site/docs/guide/Comparisons.md")],
  "9d17f7a5": [() => import(/* webpackChunkName: "9d17f7a5" */ "@site/docs/lib/README.md"), "@site/docs/lib/README.md", require.resolveWeak("@site/docs/lib/README.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "c89e169b": [() => import(/* webpackChunkName: "c89e169b" */ "@site/docs/guide/Examples.md"), "@site/docs/guide/Examples.md", require.resolveWeak("@site/docs/guide/Examples.md")],};
