// This file is generated by @hey-api/openapi-ts and rewired by heyapi-client-grab.
// Everything the SDK sends goes through grab, so caching, retries, rate limiting,
// deduplication and grab.mock apply to every endpoint below.

import { createClient, createConfig, type ClientOptions } from "heyapi-client-grab";

export const client = createClient(
  createConfig<ClientOptions>({
    baseUrl: "https://petstore3.swagger.io/api/v3",
  }),
);
